---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - uses: actions/checkout@v4
        with:
          repository: chengda/popular-fonts
          path: fonts/popular-fonts
      - uses: actions/checkout@v4
        with:
          repository: StellarCN/scp_zh
          path: fonts/scp_zh
      - uses: actions/checkout@v4
        with:
          repository: siaimes/pytorch
          path: fonts/pytorch
      - uses: actions/checkout@v4
        with:
          repository: Kangzhengwei/androidFront
          path: fonts/androidFront
      - run: |
          sudo apt-get -y update
          sudo apt-get -y install fonts-font-awesome
          install -d ~/.local/share/typst/packages/preview/modern-ustc-proposal
          mv fonts ~/.local/share
          v="$(python -c "with open('typst.toml', 'rb') as f:
            print(__import__('tomllib').load(f)['package']['version'])")"
          ln -s "$PWD" \
            ~/.local/share/typst/packages/preview/modern-ustc-proposal/"$v"
          typst compile template/*.typ
      - uses: actions/upload-artifact@v4
        with:
          path: template/*.pdf
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: template/*.pdf
